version: "3.8"

services:
  backend:
    restart: always
    build:
      context: .
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=postgres
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
    - 8000:8000
    networks:
      backend:


  postgres:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      backend:

volumes:
  postgres_data:

networks:
  backend: